config/routes.rb
Rails.application.routes.draw do

  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :entries, only: [:create , :show , :new]
  resources :comments, only: [:create , :show ]
  root  'static_pages#home'
  match '/show',  to: 'comments#show',        via: 'get'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if signed_in?
  		@entry = current_user.entries.build 
  		@feed_items = current_user.feed.paginate(page: params[:page], per_page: 5)	
  	else
  		@feed_items = Entry.paginate(page: params[:page], per_page: 5)
  	end
  	#@feed_homepages_items = Entry.paginate(page: params[:page], per_page: 5)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% if signed_in? %>
  <div class="row">
    <aside class="span4">
      <section>
        <%= render 'shared/user_info' %>
      </section>
       <section>
        <%= render 'shared/stats' %>
        </section>
      <section>
        <%= link_to "Write an Entry!", new_entry_path,
                                class: "btn btn-large btn-primary" %>
      </section>
    </aside>
    <div class="span8">
      <h3>Blogs</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center hero-unit">
    <h1>Welcome to My Blog</h1>

    <%= link_to "Sign up now!", signup_path,
                                class: "btn btn-large btn-primary" %>
  </div>
  <h1>Blog</h1>
  <%= render 'shared/feed' %>
<% end %>